services:
  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    depends_on:
#      - product-service
#      - inventory-service
#      - order-service
#      - notification-service
#
  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
  #  links:
  #    - prometheus:prometheus
  #  volumes:
  #    - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password